In [20]:
import pandas as pd

df = pd.DataFrame({
    "carbody": ["sedan","hatchback","sedan","wagon","hatchback"],
    "symboling": [0,1,0,2,1],
    "horsepower": [130,95,150,110,105],
    "citympg": [21,30,19,24,27],
    "price": [15000,12000,18000,16000,14000]
})

df

     carbody  symboling  horsepower  citympg  price
0      sedan          0         130       21  15000
1  hatchback          1          95       30  12000
2      sedan          0         150       19  18000
3      wagon          2         110       24  16000
4  hatchback          1         105       27  14000

In [29]:
X = df.drop("price", axis=1)
y = df["price"]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   carbody     5 non-null      object
 1   symboling   5 non-null      int64
 2   horsepower  5 non-null      int64
 3   citympg     5 non-null      int64
 4   price       5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=0)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=0)
numerical_columns = ["horsepower","citympg"]

In [32]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train[numerical_columns] = scaler.fit_transform(X_train[numerical_columns])
X_train[numerical_columns]

   horsepower  citympg
1    0.000000      1.0
3    1.000000      0.0
4    0.666667      0.5

In [33]:
X_val[numerical_columns] = scaler.transform(X_val[numerical_columns])
X_test[numerical_columns] = scaler.transform(X_test[numerical_columns])

In [34]:
categorical_columns = ["carbody", "symboling"]
X_train = pd.get_dummies(X_train, columns=categorical_columns, drop_first=True)
X_val   = pd.get_dummies(X_val, columns=categorical_columns, drop_first=True)
X_test  = pd.get_dummies(X_test, columns=categorical_columns, drop_first=True)

# make sure all 3 datasets have same columns
X_val = X_val.reindex(columns=X_train.columns, fill_value=0)
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

X_train

   horsepower  citympg  carbody_wagon  symboling_2
1    0.000000      1.0          False        False
3    1.000000      0.0           True         True
4    0.666667      0.5          False        False

In [28]:
X_val_dummies.columns

Index(['horsepower', 'citympg'], dtype='object')