Please remove the column containing the name of each university 
Obtain descriptive statistics on the numeric columns of the dataset using the .describe() method from Pandas 
Round these statistics to 2 decimal places using the .round() method from Pandas 
Consider ‘Grad.Rate’ as the target variable 
Do not normalise or scale the data in any way 
Do not forget to one-hot encode the ‘Private’ variable 
You can achieve this using pandas.get_dummies() 
Be sure to set drop_first = True so the redundant encoded column is excluded 
When splitting the data, please use sklearn.model_selection.train_test_split() 
Please use a 70:30 train:test split 
Please set random_state = 42 so that the results you obtain can be compared to ours 
Fit the model on the training set 
Output the model coefficients, rounded to 2 decimal places using the .round() method from Pandas 
Obtain predictions on both, the training and testing sets 
Generate the following metrics (using sklearn.metrics) on both, the training and testing sets, and round them to 2 decimal places using the round() function 
R² 
Mean Squared Error 
Mean Absolute Error

In [1]:
import pandas as pd

df = pd.read_excel("college.xlsx")

df = df.drop(columns=["Unnamed: 0"])
df.head()

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [2]:
df.describe().round(2)

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
count,777.00,777.00,777.00,777.00,777.0,777.00,777.00,777.00,777.00,777.00,777.00,777.00,777.00,777.00,777.00,777.00,777.00
mean,3001.64,2018.80,779.97,27.56,55.8,3699.91,855.30,10440.67,4357.53,549.38,1340.64,72.66,79.70,14.09,22.74,9660.17,65.46
std,3870.20,2451.11,929.18,17.64,19.8,4850.42,1522.43,4023.02,1096.70,165.11,677.07,16.33,14.72,3.96,12.39,5221.77,17.18
min,81.00,72.00,35.00,1.00,9.0,139.00,1.00,2340.00,1780.00,96.00,250.00,8.00,24.00,2.50,0.00,3186.00,10.00
25%,776.00,604.00,242.00,15.00,41.0,992.00,95.00,7320.00,3597.00,470.00,850.00,62.00,71.00,11.50,13.00,6751.00,53.00
50%,1558.00,1110.00,434.00,23.00,54.0,1707.00,353.00,9990.00,4200.00,500.00,1200.00,75.00,82.00,13.60,21.00,8377.00,65.00
75%,3624.00,2424.00,902.00,35.00,69.0,4005.00,967.00,12925.00,5050.00,600.00,1700.00,85.00,92.00,16.50,31.00,10830.00,78.00
max,48094.00,26330.00,6392.00,96.00,100.0,31643.00,21836.00,21700.00,8124.00,2340.00,6800.00,103.00,100.00,39.80,64.00,56233.00,118.00

In [3]:
df_all_numeric = pd.get_dummies(df, columns=["Private"])
df_all_numeric.head(1)

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate,Private_No,Private_Yes
0,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60,False,True

In [4]:
df_all_numeric = pd.get_dummies(df, columns=["Private"], drop_first=True)
df_all_numeric.head(1)

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate,Private_Yes
0,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60,True

In [5]:
X = df_all_numeric.drop(columns=["Grad.Rate"])
y = df["Grad.Rate"]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [9]:
coefficients = pd.Series(model.coef_, index=X.columns)
print(coefficients.round(2))
model.coef_
print(model.intercept_)

Apps           0.00
Accept        -0.00
Enroll         0.00
Top10perc      0.03
Top25perc      0.14
F.Undergrad   -0.00
P.Undergrad   -0.00
Outstate       0.00
Room.Board     0.00
Books         -0.00
Personal      -0.00
PhD            0.14
Terminal      -0.11
S.F.Ratio     -0.03
perc.alumni    0.34
Expend        -0.00
Private_Yes    5.05
dtype: float64
34.938712506221975

# Predictions

In [38]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluation Metrics

In [39]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
train_r2 = round(r2_score(y_train, y_train_pred), 2)
train_mse = round(mean_squared_error(y_train, y_train_pred), 2)
train_mae = round(mean_absolute_error(y_train, y_train_pred), 2)

print("Training Metrics")
print("R2:", train_r2)
print("MSE:", train_mse)
print("MAE:", train_mae)

Training Metrics
R2: 0.46
MSE: 160.59
MAE: 9.37

# Testing Metrics

1. Actual  `y = [10, 20, 30]`
2. Predicted  `ŷ = [12, 18, 33]`
3. Error `[2, -2, 3]`
4. SSE `2^2+(−2)^2+3^2=4+4+9=17`
5. MSE `SSE/n = 17/3 = 5.67`
6. MAE `(|2| + |3| + |3|) = 7/3 = 2.33`

In [ ]:
test_r2 = round(r2_score(y_test, y_test_pred), 2)
test_mse = round(mean_squared_error(y_test, y_test_pred), 2)
test_mae = round(mean_absolute_error(y_test, y_test_pred), 2)

print("Testing Metrics")
print("R2:", test_r2)
print("MSE:", test_mse) # = SSE / n 
print("MAE:", test_mae)

Testing Metrics
R2: 0.44
MSE: 160.48
MAE: 9.6

In [41]:
pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_test_pred
}).head()

     Actual  Predicted
568      66  57.503395
530      45  49.659529
610      54  53.989710
109      73  72.712251
586      43  55.156547